modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

# This points to the logo.png file you need to place in src/main/resources/
logoFile="logo.png"

credits="Created by VaviYT"
authors="VaviYT"

description='''
My Kaisen brings the explosive, high-speed combat of jujutsu sorcery into Minecraft! 

Current Abilities:
- Cursed Strikes: Dash forward and lock your enemies in a relentless 3-second flurry of punches.
- Divergent Fist & Black Flash (Coming Soon!)
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

# You can add issueTrackerURL or displayURL later if you upload the mod to CurseForge or GitHub!